spring:
  application:
    name: scholar
  profiles:
    active: pro # 在这里切换项目环境，dev为开发环境（服务器中的scholar数据库），pro为部署环境（服务器中的openalex数据库）
  mail:
    host: smtp.qq.com
    username: 2562187628@qq.com
    password: xtkjjggvfxdcdija
    port: 465
    protocol: smtps
    default-encoding: utf-8
    from: 2562187628@qq.com
    smtp:
      auth: true
      starttls:
        enable: true
      socketFactory:
        class: javax.net.ssl.SSLSocketFactory
server:
  port: 1145
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.cache.interceptor: DEBUG