spring:
  datasource:
    url: jdbc:mysql://116.204.112.5:3306/openalex?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: BjMfWi6CFkrW3556
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    rest:
      uris: http://localhost:9200
      connection-timeout: 1s
      read-timeout: 30s
