spring:
  application:
    name: scholar
  profiles:
    active: pro # 在这里切换项目环境，dev为开发环境（本地数据库），pro为生产环境（已连接服务器数据库）
  mail:
    host: smtp.qq.com
    username: 2142703200@qq.com
    password: htledawmoxtzcdcc
    port: 587
    protocol: smtp
    default-encoding: utf-8
    from: 2142703200@qq.com
server:
  port: 1145
mybatis:
  configuration:
    map-underscore-to-camel-case: true
