spring:
  datasource:
    url: jdbc:mysql://39.105.221.80:3306/scholar?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: scholar
    password: scholar
    driver-class-name: com.mysql.cj.jdbc.Driver