spring:
  datasource:
    url: jdbc:mysql://39.105.221.80:3306/scholar?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: scholar
    password: Ymd2WPcJhi6cGywt
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    rest:
      uris: http://localhost:9200
      connection-timeout: 1s
      read-timeout: 30s

logging:
  level:
    org:
      springframework:
        web:
          client:
            org.springframework.web.client.RestTemplate: DEBUG
        data:
          elasticsearch:
            core: DEBUG
#logging.level.org.springframework.web.client.RestTemplate=DEBUG
#
#logging.level.org.springframework.data.elasticsearch.core=DEBUG